"""
Django settings for crud_project project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()  # Load environment variables from .env file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6=y1i#$y&#sb&wo+##5r_dy#*&!h(he_iwt*qvruhu2f0@szyp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = []
# ALLOWED_HOSTS = ['crud-app.local','localhost', '127.0.0.1', 'crud-app-backend-service']

#If you want to allow any host (not recommended for production), you can use:
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'crud_app',
    'auth_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crud_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crud_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': os.getenv('DB_NAME', 'crud_app_db'),
#         'CLIENT': {
#             'host': os.getenv('MONGO_URI', 'mongo-service:27017'),
#             'username': os.getenv('MONGO_USER', 'husnain'),
#             'password': os.getenv('MONGO_PASSWORD', '35202'),
#             'authSource': os.getenv('DB_NAME', 'admin'),
#         },
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'crud_app_db',  # This is the database your app will use
        'CLIENT': {
            'host': 'mongodb://husnain:35202@crud-app-mongodb-0.mongo-service:27017,crud-app-mongodb-1.mongo-service:27017,crud-app-mongodb-2.mongo-service:27017/crud_app_db?replicaSet=rs0',  # Your MongoDB service hostname and port
            'username': 'husnain',
            'password': '35202',  # Your password
            'authSource': 'admin',  # Now authSource is crud_app_db
        },
    }
}
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': os.environ.get('DB_NAME', default='crud_app_db'),
#         'CLIENT': {
#             'host': os.environ.get('MONGO_URI'),
#             'username': os.environ.get('DB_USERNAME'),
#             'password': os.environ.get('DB_PASSWORD'),
#             'authSource': os.environ.get('DB_AUTH_SOURCE', default='admin'),
#         },
#     }
# }

#
# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'crud_app_db',
#         'CLIENT': {
#             'host': 'mongodb://husnain:35202@mongo-service:27017/crud_app_db',  # Use mongo-service
#             'port': 27017,
#             'username': 'husnain',
#             'password': '35202',
#             'authSource': 'admin',
#         }
#     }
# }



# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'crud_app_db',
#         'CLIENT': {
#             'host': 'mongo-service:27017',
#             'username': 'husnain',
#             'password': '35202',
#             'authSource': 'crud_app_db',
#         },
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'djongo',
#         'NAME': 'crud_app_db',
#         'HOST': 'localhost',
#         'PORT': 27017,
#     }
# }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
